from recipes import Ingredient, Recipe, ShoppingList, DietaryRecipe

lasagna = Recipe("Лазанья")

lasagna.add_ingredient(Ingredient("Листы для лазаньи", 250, "г"))
lasagna.add_ingredient(Ingredient("Фарш мясной говяжий", 450, "г"))
lasagna.add_ingredient(Ingredient("Лук репчатый", 1, "шт."))
lasagna.add_ingredient(Ingredient("Морковь", 1, "шт."))
lasagna.add_ingredient(Ingredient("Томатный соус", 60, "г"))
lasagna.add_ingredient(Ingredient("Томатная паста", 60, "г"))
lasagna.add_ingredient(Ingredient("Масло сливочное", 90, "г"))
lasagna.add_ingredient(Ingredient("Мука", 60, "г"))
lasagna.add_ingredient(Ingredient("Молоко", 800, "мл"))
lasagna.add_ingredient(Ingredient("Сыр пармезан", 120, "г"))
lasagna.add_ingredient(Ingredient("Мускатный орех", 1, "ч. л."))
lasagna.add_ingredient(Ingredient("Соль", 2, "ч. л."))
lasagna.add_ingredient(Ingredient("Перец молотый", 1, "ч. л."))

print("Обычный рецепт:")
print(lasagna)
print()
print("Рецепт на 2 порции:")
scaled_lasagna = lasagna.scale(2)
print(scaled_lasagna)
print()
print("Список покупок:")
shopping_list = ShoppingList()
shopping_list.add_recipe(lasagna, 2)

for ingredient in shopping_list.get_list():
    print(ingredient)
print()
print("Диетический рецепт:")
diet_lasagna = DietaryRecipe("Овощная лазанья", "вегетарианская")
diet_lasagna.add_ingredient(Ingredient("Листы для лазаньи", 250, "г"))
diet_lasagna.add_ingredient(Ingredient("Кабачок", 300, "г"))
diet_lasagna.add_ingredient(Ingredient("Морковь", 1, "шт."))
diet_lasagna.add_ingredient(Ingredient("Томатный соус", 100, "г"))
diet_lasagna.add_ingredient(Ingredient("Сыр пармезан", 100, "г"))
print(diet_lasagna)
